#!/usr/bin/env python3
"""parallax_cloud.py - draws the turbo build's parallax cloud into
data/parallax.asm (src/parallax.asm draws it over the map).

    python3 tools/art/parallax_cloud.py

The cloud is PARA_W x PARA_H chars of multicolour pixels that are only ever
'11' (the cloud: its cells' colour RAM colour, white) or '00' (clear), so
src/parallax.asm can lay it over a map char with a plain OR. It is stored as
PARA_W column strips of PARA_H * 8 rows, padded with 8 clear rows above and
below, so a cell at any pixel offset reads 8 rows from its strip without
bounds checks.
"""
import math, os, random

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "data", "parallax.asm")
W, H = 6, 3                             # chars (PARA_W, PARA_H in src/parallax.asm)
PAD = 8

rng = random.Random(1946)


def cloud():
    """[H * 8][W * 4] of 0 / 1: a cumulus, flat-bottomed, lobes on top, its
    rim dithered (screen pixels: a fat pixel is 2 wide)."""
    W2, H2 = W * 8, H * 8
    base = H2 - 1.5
    lobes = [(W2 * 0.22, H2 * 0.62, H2 * 0.36), (W2 * 0.45, H2 * 0.45, H2 * 0.46),
             (W2 * 0.70, H2 * 0.55, H2 * 0.40), (W2 * 0.86, H2 * 0.70, H2 * 0.26)]
    rb = H2 * 0.28
    out = []
    for y in range(H2):
        row = []
        for fx in range(W * 4):
            sx, sy = fx * 2 + 1, y + 0.5
            px = min(max(sx, rb + 2), W2 - rb - 2)
            d = rb - math.hypot(sx - px, sy - (base - rb))
            d = max([d] + [r - math.hypot(sx - x, sy - yy) for x, yy, r in lobes])
            d = min(d, base - sy + 1.0)
            if d <= 0:
                row.append(0)
            elif d < 1.7:
                row.append(1 if (fx + y) % 2 == 0 else 0)    # the dithered rim
            else:
                row.append(1)
        out.append(row)
    return out


def main():
    pic = cloud()
    lines = ["; data/parallax.asm: generated by tools/art/parallax_cloud.py. Don't edit.",
             "; The turbo build's parallax cloud (src/parallax.asm): PARA_W column strips,",
             "; each PARA_H * 8 rows of multicolour pixels ('11' cloud, '00' clear) with",
             f"; {PAD} clear rows above and below.", ";"]
    for y, row in enumerate(pic):
        lines.append(";   " + "".join("#" if p else "." for p in row))
    lines.append("para_strips")
    strips = []
    for c in range(W):
        col = [0] * PAD
        for y in range(H * 8):
            b = 0
            for x in range(4):
                b = b << 2 | (3 if pic[y][c * 4 + x] else 0)
            col.append(b)
        col += [0] * PAD
        strips.append(col)
        lines.append(f"        !byte " + ", ".join(f"${b:02x}" for b in col) + f"   ; column {c}")
    lines.append(f"PARA_STRIP = {H * 8 + 2 * PAD}          ; bytes per strip")
    # para_ne: for each of the H + 1 char rows a cloud can touch and each
    # pixel offset 0-7, a bit per column: does that cell show any cloud?
    # (src/parallax.asm leaves the others alone)
    lines.append("para_ne                         ; [row * 8 + offset]: bit c = column c")
    for cr in range(H + 1):
        row = []
        for sub in range(8):
            bits = 0
            for c in range(W):
                top = PAD + cr * 8 - sub
                if any(strips[c][top + y] for y in range(8)):
                    bits |= 1 << c
            row.append(bits)
        lines.append("        !byte " + ", ".join(f"%{b:08b}" for b in row) + f"   ; row {cr}")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"parallax_cloud: {W}x{H} chars -> {OUT}")


if __name__ == "__main__":
    main()
