#!/usr/bin/env python3
"""png2sprites.py - multicolour sprite sheets <-> +spr text art.

  python3 tools/png2sprites.py sheet.json out.asm
      sheet PNG -> ACME source in data/sprites.asm's format (+spr rows), so
      the result can be read, diffed and included like hand-written sprites
  python3 tools/png2sprites.py --export data/sprites.asm sheet.png [sheet.json]
      the other way: every sprite in an ACME file -> a PNG sheet (+ JSON),
      to repaint existing sprites in a paint program

THE SHEET
  A grid of cells, each one multicolour sprite: 12 x 21 pixels (or 24 x 21
  with every pixel doubled), left to right, top to bottom, no gaps.
  Pixels: transparent (alpha 0, or the JSON's "transparent" colour), white
  and dark grey (the shared sprite colours, $D025/$D026: 'w' and 'd'), and
  ONE more colour per sprite: its own colour, 'i' (set in the game per slot).
THE JSON
  {"png": "enemies.png", "cols": 8, "transparent": "#ff00ff",
   "sprites": ["fighter", "leader", ...]}       (cells in order; "" = skip)
Each sprite becomes  spr_<name> / PTR_<NAME> / +spr_begin ... +spr_end.
"""
import json, os, re, sys
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from c64gfx import ColourMatcher, PEPTO, NAMES

W, H = 12, 21
SHARED = {1: "w", 11: "d"}           # SPR_SHARED1 / SPR_SHARED2 in src/defs.asm


def fail(msg):
    sys.exit("png2sprites: " + msg)


def import_sheet(cfg_path, out_path):
    cfg = json.load(open(cfg_path))
    path = os.path.join(os.path.dirname(cfg_path), cfg["png"])
    im = Image.open(path).convert("RGBA")
    px = im.load()
    sw = im.size[0]
    scale = 2 if sw % 24 == 0 and cfg.get("doubled") else 1
    cols = cfg.get("cols") or im.size[0] // (W * scale)
    key = cfg.get("transparent")
    key = tuple(int(key[i:i + 2], 16) for i in (1, 3, 5)) if key else None
    match = ColourMatcher()
    out = [f"; {out_path}: generated by tools/png2sprites.py from {cfg_path}. Don't edit."]
    for n, name in enumerate(cfg["sprites"]):
        if not name:
            continue
        cx, cy = (n % cols) * W * scale, (n // cols) * H
        if cy + H > im.size[1] or cx + W * scale > im.size[0]:
            fail(f"sprite {n} ({name}) is outside the sheet")
        own, rows = None, []
        for y in range(H):
            row = ""
            for x in range(W):
                r, g, b, a = px[cx + x * scale, cy + y]
                if a == 0 or (key and (r, g, b) == key):
                    row += "."
                    continue
                c = match((r, g, b))
                if c in SHARED:
                    row += SHARED[c]
                    continue
                if own is None:
                    own = c
                elif c != own:
                    fail(f"sprite {name} uses two own colours ({NAMES[own]}, {NAMES[c]}); "
                         "only one besides white and dark grey")
                row += "i"
            rows.append(row)
        out.append(f"\nspr_{name}")
        out.append(f"PTR_{name.upper()} = SPR_PTR0 + (spr_{name} - SPRITES) / 64")
        if own is not None:
            out.append(f"COL_SPR_{name.upper()} = {own}          ; {NAMES[own]}: its 'i' colour")
        out.append("        +spr_begin")
        out += [f'        +spr "{r}"     ; {i:2}' for i, r in enumerate(rows)]
        out.append("        +spr_end")
    open(out_path, "w").write("\n".join(out) + "\n")
    print(f"png2sprites: {len([s for s in cfg['sprites'] if s])} sprites -> {out_path}")


def export_sheet(asm_path, png_path, json_path=None, cols=8):
    sprites, name, rows = [], None, []
    for line in open(asm_path):
        m = re.match(r"^spr_(\w+)\s*$", line)
        if m:
            name, rows = m.group(1), []
            continue
        m = re.match(r'^\s+\+spr\s+"(.{12})"', line)
        if m and name:
            rows.append(m.group(1))
            if len(rows) == H:
                sprites.append((name, rows))
                name = None
    if not sprites:
        fail(f"no +spr sprites found in {asm_path}")
    own = PEPTO[15]                   # light grey stands in for 'i'
    colour = {"w": PEPTO[1] + (255,), "d": PEPTO[11] + (255,), "i": own + (255,),
              ".": (0, 0, 0, 0)}
    rows_n = (len(sprites) + cols - 1) // cols
    im = Image.new("RGBA", (cols * W, rows_n * H), (0, 0, 0, 0))
    px = im.load()
    for n, (nm, rr) in enumerate(sprites):
        cx, cy = (n % cols) * W, (n // cols) * H
        for y, r in enumerate(rr):
            for x, ch in enumerate(r):
                px[cx + x, cy + y] = colour[ch]
    im.save(png_path)
    if json_path:
        json.dump({"png": os.path.basename(png_path), "cols": cols,
                   "sprites": [nm for nm, _ in sprites]}, open(json_path, "w"), indent=1)
    print(f"png2sprites: {len(sprites)} sprites -> {png_path}")


if __name__ == "__main__":
    a = sys.argv[1:]
    if len(a) >= 3 and a[0] == "--export":
        export_sheet(a[1], a[2], a[3] if len(a) > 3 else None)
    elif len(a) == 2:
        import_sheet(*a)
    else:
        sys.exit(__doc__)
